In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
df = pd.read_excel('flight_price.xlsx')
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [ ]:
df.tail()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [ ]:
df.describe()

              Price
count  10683.000000
mean    9087.064121
std     4611.359167
min     1759.000000
25%     5277.000000
50%     8372.000000
75%    12373.000000
max    79512.000000

In [ ]:
df.shape

(10683, 11)

In [ ]:
df.head(2)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662

In [ ]:
# Feature Engg. - Data Cleaning
df['Date'] = df['Date_of_Journey'].str.split('/').str[0]
df['Month'] = df['Date_of_Journey'].str.split('/').str[1]
df['Year'] = df['Date_of_Journey'].str.split('/').str[2]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
 11  Date             10683 non-null  object
 12  Month            10683 non-null  object
 13  Year             10683 non-null  object
dtypes: int64(1), object(13)
memory usage: 1.1+ MB

In [ ]:
df['Date'] = df['Date'].astype('int')
df['Month'] = df['Month'].astype('int')
df['Year'] = df['Year'].astype('int')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
 11  Date             10683 non-null  int64
 12  Month            10683 non-null  int64
 13  Year             10683 non-null  int64
dtypes: int64(4), object(10)
memory usage: 1.1+ MB

In [ ]:
df.drop('Date_of_Journey', axis=1, inplace=True)

In [ ]:
df.head(2)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019

In [ ]:
df['Arrival_Time'] = df['Arrival_Time'].apply(lambda x:x.split(' ')[0])

In [ ]:
df['Arrival_Hour'] = df['Arrival_Time'].str.split(':').str[0]
df['Arrival_Min'] = df['Arrival_Time'].str.split(':').str[1]
df['Arrival_Hour'] = df['Arrival_Hour'].astype('int')
df['Arrival_Min'] = df['Arrival_Min'].astype('int')

In [ ]:
df.drop('Arrival_Time', axis=1, inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Route            10682 non-null  object
 4   Dep_Time         10683 non-null  object
 5   Duration         10683 non-null  object
 6   Total_Stops      10682 non-null  object
 7   Additional_Info  10683 non-null  object
 8   Price            10683 non-null  int64
 9   Date             10683 non-null  int64
 10  Month            10683 non-null  int64
 11  Year             10683 non-null  int64
 12  Arrival_Hour     10683 non-null  int64
 13  Arrival_Min      10683 non-null  int64
dtypes: int64(6), object(8)
memory usage: 1.1+ MB

In [ ]:
df.head(2)

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Min
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,2h 50m,non-stop,No info,3897,24,3,2019,1,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,7h 25m,2 stops,No info,7662,1,5,2019,13,15

In [ ]:
df['Dept_Hour'] = df['Dep_Time'].str.split(':').str[0]
df['Dept_Min'] = df['Dep_Time'].str.split(':').str[1]
df['Dept_Hour'] = df['Dept_Hour'].astype('int')
df['Dept_Min'] = df['Dept_Min'].astype('int')
df.drop('Dep_Time', axis=1, inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Route            10682 non-null  object
 4   Duration         10683 non-null  object
 5   Total_Stops      10682 non-null  object
 6   Additional_Info  10683 non-null  object
 7   Price            10683 non-null  int64
 8   Date             10683 non-null  int64
 9   Month            10683 non-null  int64
 10  Year             10683 non-null  int64
 11  Arrival_Hour     10683 non-null  int64
 12  Arrival_Min      10683 non-null  int64
 13  Dept_Hour        10683 non-null  int64
 14  Dept_Min         10683 non-null  int64
dtypes: int64(8), object(7)
memory usage: 1.2+ MB

In [ ]:
df.head(2)

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Min,Dept_Hour,Dept_Min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662,1,5,2019,13,15,5,50

In [ ]:
df['Duration_Hour'] = df['Duration'].str.split(' ').str[0].str.split('h').str[0]
df['Duration_Min'] = df['Duration'].str.split(' ').str[1].str.split('m').str[0]

In [ ]:
df['Duration_Hour'] = df['Duration_Hour'].astype('int')
df['Duration_Min'] = df['Duration_Min'].astype('int')
df.drop('Duration', axis=1, inplace=True)

ValueError: invalid literal for int() with base 10: '5m'

In [ ]:
df[['Duration_Hour', 'Duration_Min']].isnull().sum()

Duration_Hour       0
Duration_Min     1032
dtype: int64

In [ ]:
df['Duration_Hour'] = df['Duration_Hour'].fillna(0)
df['Duration_Min'] = df['Duration_Min'].fillna(0)
df[['Duration_Hour', 'Duration_Min']].isnull().sum()

Duration_Hour    0
Duration_Min     0
dtype: int64

In [ ]:
df['Duration_Hour'].unique()

array(['2', '7', '19', '5', '4', '15', '21', '25', '13', '12', '26', '22',
       '23', '20', '10', '6', '11', '8', '16', '3', '27', '1', '14', '9',
       '18', '17', '24', '30', '28', '29', '37', '34', '38', '35', '36',
       '47', '33', '32', '31', '42', '39', '5m', '41', '40'], dtype=object)

In [ ]:
df[df['Duration_Hour'].str.isnumeric() == False]

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Min,Dept_Hour,Dept_Min,Duration_Hour,Duration_Min
6474,Air India,Mumbai,Hyderabad,BOM → GOI → PNQ → HYD,5m,2 stops,No info,17327,6,3,2019,16,55,16,50,5m,0

In [ ]:
df.drop(index=6474, inplace=True)

In [ ]:
6474 in df.index

False

In [ ]:
df['Duration_Hour'] = df['Duration_Hour'].astype('int')
df['Duration_Min'] = df['Duration_Min'].astype('int')
df.drop('Duration', axis=1, inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Route            10681 non-null  object
 4   Total_Stops      10681 non-null  object
 5   Additional_Info  10682 non-null  object
 6   Price            10682 non-null  int64
 7   Date             10682 non-null  int64
 8   Month            10682 non-null  int64
 9   Year             10682 non-null  int64
 10  Arrival_Hour     10682 non-null  int64
 11  Arrival_Min      10682 non-null  int64
 12  Dept_Hour        10682 non-null  int64
 13  Dept_Min         10682 non-null  int64
 14  Duration_Hour    10682 non-null  int64
 15  Duration_Min     10682 non-null  int64
dtypes: int64(10), object(6)
memory usage: 1.6+ MB

In [ ]:
df['Total_Duration(min)'] = (df['Duration_Hour']*60) + df['Duration_Min']

In [ ]:
df.head(2)

,Airline,Source,Destination,Route,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Min,Dept_Hour,Dept_Min,Duration_Hour,Duration_Min,Duration(min),Total_Duration(min)
0,IndiGo,Banglore,New Delhi,BLR → DEL,non-stop,No info,3897,24,3,2019,1,10,22,20,2,50,170,170
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2 stops,No info,7662,1,5,2019,13,15,5,50,7,25,445,445

In [ ]:
df['Total_Duration(min)'].dtype

dtype('int64')

In [ ]:
df['Total_Stops'] = df['Total_Stops'].map({'non-stop':0,
                                           '2 stops':2,
                                           '1 stop':1,
                                           '3 stops':3,
                                           '4 stops':4})

In [ ]:
df['Total_Stops'].unique()

array([ 0.,  2.,  1.,  3., nan,  4.])

In [ ]:
df['Total_Stops'].isnull().sum()

np.int64(1)

In [ ]:
#df['Total_Stops'].fillna(df['Total_Stops'].mean(), inplace=True)
df['Total_Stops'] = df['Total_Stops'].fillna(df['Total_Stops'].mode()[0])
df['Total_Stops'] = df['Total_Stops'].astype('int')

In [ ]:
df['Total_Stops'].mode()

0    1.0
Name: Total_Stops, dtype: float64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Airline              10682 non-null  object
 1   Source               10682 non-null  object
 2   Destination          10682 non-null  object
 3   Route                10681 non-null  object
 4   Total_Stops          10682 non-null  int64
 5   Additional_Info      10682 non-null  object
 6   Price                10682 non-null  int64
 7   Date                 10682 non-null  int64
 8   Month                10682 non-null  int64
 9   Year                 10682 non-null  int64
 10  Arrival_Hour         10682 non-null  int64
 11  Arrival_Min          10682 non-null  int64
 12  Dept_Hour            10682 non-null  int64
 13  Dept_Min             10682 non-null  int64
 14  Duration_Hour        10682 non-null  int64
 15  Duration_Min         10682 non-null  int64
 16  Duration(min)        10682 non-null  int64
 17  Total_Duration(min)  10682 non-null  int64
dtypes: int64(13), object(5)
memory usage: 1.8+ MB

In [ ]:
df['Additional_Info'].head(4)

0    No info
1    No info
2    No info
3    No info
Name: Additional_Info, dtype: object

In [ ]:
df['Additional_Info'].unique()

array(['No info', 'In-flight meal not included',
       'No check-in baggage included', '1 Short layover', 'No Info',
       '1 Long layover', 'Change airports', 'Business class',
       'Red-eye flight', '2 Long layover'], dtype=object)

In [ ]:
df['Airline'].unique()

array(['IndiGo', 'Air India', 'Jet Airways', 'SpiceJet',
       'Multiple carriers', 'GoAir', 'Vistara', 'Air Asia',
       'Vistara Premium economy', 'Jet Airways Business',
       'Multiple carriers Premium economy', 'Trujet'], dtype=object)

In [ ]:
df['Source'].unique()

array(['Banglore', 'Kolkata', 'Delhi', 'Chennai', 'Mumbai'], dtype=object)

In [ ]:
df.drop('Route',axis=1, inplace=True)

In [ ]:
df['Destination'].unique()

array(['New Delhi', 'Banglore', 'Cochin', 'Kolkata', 'Delhi', 'Hyderabad'],
      dtype=object)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Airline              10682 non-null  object
 1   Source               10682 non-null  object
 2   Destination          10682 non-null  object
 3   Total_Stops          10682 non-null  int64
 4   Additional_Info      10682 non-null  object
 5   Price                10682 non-null  int64
 6   Date                 10682 non-null  int64
 7   Month                10682 non-null  int64
 8   Year                 10682 non-null  int64
 9   Arrival_Hour         10682 non-null  int64
 10  Arrival_Min          10682 non-null  int64
 11  Dept_Hour            10682 non-null  int64
 12  Dept_Min             10682 non-null  int64
 13  Duration_Hour        10682 non-null  int64
 14  Duration_Min         10682 non-null  int64
 15  Duration(min)        10682 non-null  int64
 16  Total_Duration(min)  10682 non-null  int64
dtypes: int64(13), object(4)
memory usage: 1.7+ MB

In [ ]:
df['Additional_Info'].unique().tolist()

['No info',
 'In-flight meal not included',
 'No check-in baggage included',
 '1 Short layover',
 'No Info',
 '1 Long layover',
 'Change airports',
 'Business class',
 'Red-eye flight',
 '2 Long layover']

In [ ]:
# No Info and No info are same
df['Additional_Info'] = df['Additional_Info'].str.lower()

In [ ]:
df['Additional_Info'].unique().tolist()

['no info',
 'in-flight meal not included',
 'no check-in baggage included',
 '1 short layover',
 '1 long layover',
 'change airports',
 'business class',
 'red-eye flight',
 '2 long layover']

In [ ]:
df['Additional_Info'].value_counts()  #(normalize=True)

Additional_Info
no info                         8347
in-flight meal not included     1982
no check-in baggage included     320
1 long layover                    19
change airports                    7
business class                     4
1 short layover                    1
red-eye flight                     1
2 long layover                     1
Name: count, dtype: int64

In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# Define categorical columns (IMPORTANT: list of strings, not tuple)
categorical_cols = ['Airline', 'Source', 'Destination', 'Additional_Info']

# Create OneHotEncoder object
encoder = OneHotEncoder(sparse_output=False, drop='first')

# Fit and transform categorical columns
encoded = encoder.fit_transform(df[categorical_cols])

# Convert encoded array to DataFrame
encoded_df = pd.DataFrame(
    encoded,
    columns=encoder.get_feature_names_out(categorical_cols),
    index=df.index
)

# Drop original categorical columns
df_numeric = df.drop(columns=categorical_cols)

# Combine numeric data + encoded data
df_final = pd.concat([df_numeric, encoded_df], axis=1)

# Check result
print("Final shape:", df_final.shape)
print("\nData types:\n", df_final.dtypes)

Final shape: (10682, 42)

Data types:
 Total_Stops                                       int64
Price                                             int64
Date                                              int64
Month                                             int64
Year                                              int64
Arrival_Hour                                      int64
Arrival_Min                                       int64
Dept_Hour                                         int64
Dept_Min                                          int64
Duration_Hour                                     int64
Duration_Min                                      int64
Duration(min)                                     int64
Total_Duration(min)                               int64
Additinal_Info                                   object
Airline_Air India                               float64
Airline_GoAir                                   float64
Airline_IndiGo                                  float64
Airline_Jet Airways                             float64
Airline_Jet Airways Business                    float64
Airline_Multiple carriers                       float64
Airline_Multiple carriers Premium economy       float64
Airline_SpiceJet                                float64
Airline_Trujet                                  float64
Airline_Vistara                                 float64
Airline_Vistara Premium economy                 float64
Source_Chennai                                  float64
Source_Delhi                                    float64
Source_Kolkata                                  float64
Source_Mumbai                                   float64
Destination_Cochin                              float64
Destination_Delhi                               float64
Destination_Hyderabad                           float64
Destination_Kolkata                             float64
Destination_New Delhi                           float64
Additional_Info_1 short layover                 float64
Additional_Info_2 long layover                  float64
Additional_Info_business class                  float64
Additional_Info_change airports                 float64
Additional_Info_in-flight meal not included     float64
Additional_Info_no check-in baggage included    float64
Additional_Info_no info                         float64
Additional_Info_red-eye flight                  float64
dtype: object

In [ ]:
df_final.columns.tolist()

['Total_Stops',
 'Price',
 'Date',
 'Month',
 'Year',
 'Arrival_Hour',
 'Arrival_Min',
 'Dept_Hour',
 'Dept_Min',
 'Duration_Hour',
 'Duration_Min',
 'Duration(min)',
 'Total_Duration(min)',
 'Additinal_Info',
 'Airline_Air India',
 'Airline_GoAir',
 'Airline_IndiGo',
 'Airline_Jet Airways',
 'Airline_Jet Airways Business',
 'Airline_Multiple carriers',
 'Airline_Multiple carriers Premium economy',
 'Airline_SpiceJet',
 'Airline_Trujet',
 'Airline_Vistara',
 'Airline_Vistara Premium economy',
 'Source_Chennai',
 'Source_Delhi',
 'Source_Kolkata',
 'Source_Mumbai',
 'Destination_Cochin',
 'Destination_Delhi',
 'Destination_Hyderabad',
 'Destination_Kolkata',
 'Destination_New Delhi',
 'Additional_Info_1 short layover',
 'Additional_Info_2 long layover',
 'Additional_Info_business class',
 'Additional_Info_change airports',
 'Additional_Info_in-flight meal not included',
 'Additional_Info_no check-in baggage included',
 'Additional_Info_no info',
 'Additional_Info_red-eye flight']